export const EXERCISES = [
  {
    workout: "A",
    slug: "goblet-squat",
    name: "Goblet Squat",
    subtitle: "Legs + core",
    sets: "3 × 12–15",
    rest: 90,
    progression: { type: "reps", sets: 3, repMin: 12, repMax: 15, usesDumbbells: true },
    substitutes: [{ slug: "sit-to-stand", label: "Sit-to-Stand", reason: "Lower stress on knees and balance" }],
    instructions: "Hold one dumbbell vertically at your chest. Squat down until your thighs are at least near parallel, then drive through your heels to stand back up.",
    cues: ["Keep chest tall", "Lower for about 3 seconds", "Knees track over toes", "Keep the dumbbell close"],
    video: "https://www.acefitness.org/resources/everyone/exercise-library/362/goblet-squat/"
  },
  {
    workout: "A",
    slug: "floor-press",
    name: "Dumbbell Floor Press",
    subtitle: "Chest + triceps",
    sets: "3 × 10–15",
    rest: 75,
    progression: { type: "reps", sets: 3, repMin: 10, repMax: 15, usesDumbbells: true },
    substitutes: [{ slug: "seated-chest-press", label: "Seated Chest Press", reason: "More back support, less shoulder strain" }],
    instructions: "Lie on the floor with knees bent and dumbbells at chest level. Press until arms are straight, then lower until upper arms lightly touch the floor.",
    cues: ["Wrists stacked over elbows", "Control the lowering", "Do not bounce off the floor", "Keep shoulder blades tucked"],
    video: "https://www.youtube.com/results?search_query=dumbbell+floor+press"
  },
  {
    workout: "A",
    slug: "overhead-press",
    name: "Overhead Press",
    subtitle: "Shoulders + triceps",
    sets: "3 × 10–12",
    rest: 75,
    progression: { type: "reps", sets: 3, repMin: 10, repMax: 12, usesDumbbells: true },
    substitutes: [{ slug: "seated-dumbbell-press", label: "Seated Dumbbell Press", reason: "Back support, less balance demand" }],
    instructions: "Start with dumbbells at shoulder height. Brace your core and press overhead until your arms are extended. Lower with control.",
    cues: ["Ribs down", "Do not lean back", "Press up and slightly back", "Slow lowering"],
    video: "https://www.youtube.com/results?search_query=standing+dumbbell+overhead+press"
  },
  {
    workout: "A",
    slug: "reverse-lunge",
    name: "Reverse Lunge",
    subtitle: "Legs + balance",
    sets: "3 × 10/leg",
    rest: 90,
    progression: { type: "reps_per_side", sets: 3, repMin: 8, repMax: 10, usesDumbbells: true },
    substitutes: [
      { slug: "supported-split-squat", label: "Supported Split Squat", reason: "Hold a chair for balance" },
      { slug: "sit-to-stand", label: "Sit-to-Stand", reason: "Simplest lower-body option" }
    ],
    instructions: "Step one foot back, lower under control, then push through your front heel to stand up. Start bodyweight if needed.",
    cues: ["Long step back", "Front foot stays planted", "Front knee stays controlled", "Use dumbbells only when stable"],
    video: "https://www.youtube.com/results?search_query=dumbbell+reverse+lunge"
  },
  {
    workout: "A",
    slug: "farmer-carry",
    name: "Farmer Carry",
    subtitle: "Grip + core",
    sets: "3 × 30–45 sec",
    rest: 60,
    progression: { type: "time", sets: 3, usesDumbbells: true },
    substitutes: [{ slug: "supported-march-in-place", label: "Supported March in Place", reason: "Hold a wall or chair, lighter load on balance" }],
    instructions: "Hold a dumbbell in each hand and walk tall. Keep your shoulders down, core tight, and steps steady.",
    cues: ["Tall posture", "Short steady steps", "Do not shrug", "Brace like someone might bump you"],
    video: "https://www.youtube.com/results?search_query=dumbbell+farmer+carry"
  },
  {
    workout: "B",
    slug: "one-arm-row",
    name: "One-Arm Row",
    subtitle: "Back + biceps",
    sets: "3 × 12–15/arm",
    rest: 75,
    progression: { type: "reps_per_side", sets: 3, repMin: 12, repMax: 15, usesDumbbells: true },
    substitutes: [{ slug: "chest-supported-row", label: "Chest-Supported Row", reason: "More back support, less core demand" }],
    instructions: "Place one hand on a chair or couch. Keep your back flat and row the dumbbell toward your hip.",
    cues: ["Pull toward hip", "Do not twist", "Pause at the top", "Lower fully"],
    video: "https://www.youtube.com/results?search_query=one+arm+dumbbell+row"
  },
  {
    workout: "B",
    slug: "chest-supported-row",
    name: "Chest-Supported Row",
    subtitle: "Upper back",
    sets: "3 × 12–15",
    rest: 75,
    progression: { type: "reps", sets: 3, repMin: 12, repMax: 15, usesDumbbells: true },
    substitutes: [{ slug: "one-arm-row", label: "One-Arm Row", reason: "Lighter weight, supported by chair" }],
    instructions: "Lie chest-down on a sturdy inclined surface. Row dumbbells up toward your lower chest or ribs.",
    cues: ["Chest stays supported", "Squeeze shoulder blades", "Do not shrug", "Lower with control"],
    video: "https://www.youtube.com/results?search_query=chest+supported+dumbbell+row"
  },
  {
    workout: "B",
    slug: "romanian-deadlift",
    name: "Romanian Deadlift",
    subtitle: "Hamstrings + glutes",
    sets: "3 × 15",
    rest: 90,
    progression: { type: "reps", sets: 3, repMin: 12, repMax: 15, usesDumbbells: true },
    substitutes: [{ slug: "reduced-range-hip-hinge", label: "Reduced-Range Hip Hinge", reason: "Shorter range, lighter load on lower back" }],
    instructions: "Hold dumbbells in front of your thighs. Hinge at the hips, lower the weights down your legs, then stand by squeezing glutes.",
    cues: ["Hips back", "Flat back", "Soft knees", "Feel hamstrings stretch"],
    video: "https://www.youtube.com/results?search_query=dumbbell+romanian+deadlift"
  },
  {
    workout: "B",
    slug: "hammer-curl",
    name: "Hammer Curl",
    subtitle: "Biceps + forearms",
    sets: "3 × 12–15",
    rest: 60,
    progression: { type: "reps", sets: 3, repMin: 12, repMax: 15, usesDumbbells: true },
    substitutes: [{ slug: "seated-hammer-curl", label: "Seated Hammer Curl", reason: "Seated position reduces swinging" }],
    instructions: "Hold dumbbells with palms facing each other. Curl without swinging, then lower slowly.",
    cues: ["Elbows stay near sides", "Palms face inward", "No body swing", "Slow on the way down"],
    video: "https://www.youtube.com/results?search_query=dumbbell+hammer+curl"
  },
  {
    workout: "B",
    slug: "tricep-extension",
    name: "Overhead Tricep Extension",
    subtitle: "Triceps",
    sets: "3 × 12–15",
    rest: 60,
    progression: { type: "reps", sets: 3, repMin: 12, repMax: 15, usesDumbbells: true },
    substitutes: [{ slug: "tricep-kickback", label: "Tricep Kickback", reason: "Less shoulder mobility required" }],
    instructions: "Hold one dumbbell overhead with both hands. Lower behind your head by bending your elbows, then extend back up.",
    cues: ["Elbows mostly forward", "Get a full stretch", "Do not arch your back", "Move at the elbows"],
    video: "https://www.youtube.com/results?search_query=dumbbell+overhead+tricep+extension"
  },
  {
    workout: "sub",
    slug: "sit-to-stand",
    name: "Sit-to-Stand",
    subtitle: "Legs (substitute)",
    sets: "3 × 10–15",
    rest: 75,
    progression: { type: "reps", sets: 3, repMin: 10, repMax: 15, usesDumbbells: false },
    imageSlug: "goblet-squat",
    instructions: "Sit on a sturdy chair. Stand up without using your hands if comfortable, then lower back down with control.",
    cues: ["Feet hip-width", "Lean slightly forward", "Drive through heels", "Use hands only if needed"],
    video: "https://www.youtube.com/results?search_query=sit+to+stand+exercise"
  },
  {
    workout: "sub",
    slug: "supported-split-squat",
    name: "Supported Split Squat",
    subtitle: "Legs + balance (substitute)",
    sets: "3 × 8–10/leg",
    rest: 90,
    progression: { type: "reps_per_side", sets: 3, repMin: 8, repMax: 10, usesDumbbells: true },
    imageSlug: "reverse-lunge",
    instructions: "Hold a chair or wall for balance. Step one foot back into a split stance and lower under control, then stand.",
    cues: ["Light hand on support", "Front knee stays over ankle", "Torso tall", "Move slowly"],
    video: "https://www.youtube.com/results?search_query=supported+split+squat"
  },
  {
    workout: "sub",
    slug: "seated-dumbbell-press",
    name: "Seated Dumbbell Press",
    subtitle: "Shoulders (substitute)",
    sets: "3 × 10–12",
    rest: 75,
    progression: { type: "reps", sets: 3, repMin: 10, repMax: 12, usesDumbbells: true },
    imageSlug: "overhead-press",
    instructions: "Sit tall on a bench or chair with back support. Press dumbbells overhead, then lower with control.",
    cues: ["Back supported", "Ribs down", "Press straight up", "No leaning back"],
    video: "https://www.youtube.com/results?search_query=seated+dumbbell+shoulder+press"
  },
  {
    workout: "sub",
    slug: "reduced-range-hip-hinge",
    name: "Reduced-Range Hip Hinge",
    subtitle: "Hamstrings (substitute)",
    sets: "3 × 12–15",
    rest: 75,
    progression: { type: "reps", sets: 3, repMin: 12, repMax: 15, usesDumbbells: true },
    imageSlug: "romanian-deadlift",
    instructions: "Hold light dumbbells. Hinge only until you feel a mild hamstring stretch, then stand tall. Use a shorter range than a full RDL.",
    cues: ["Small hip movement", "Flat back", "Soft knees", "Stop before discomfort"],
    video: "https://www.youtube.com/results?search_query=dumbbell+hip+hinge"
  },
  {
    workout: "sub",
    slug: "supported-march-in-place",
    name: "Supported March in Place",
    subtitle: "Core + grip (substitute)",
    sets: "3 × 30–45 sec",
    rest: 60,
    progression: { type: "time", sets: 3, usesDumbbells: true },
    imageSlug: "farmer-carry",
    instructions: "Hold light dumbbells and lightly touch a wall or chair. March in place with tall posture and steady breathing.",
    cues: ["Light fingertip support", "Knees lift comfortably", "Shoulders down", "Breathe steadily"],
    video: "https://www.youtube.com/results?search_query=march+in+place+exercise"
  },
  {
    workout: "sub",
    slug: "seated-chest-press",
    name: "Seated Chest Press",
    subtitle: "Chest (substitute)",
    sets: "3 × 10–15",
    rest: 75,
    progression: { type: "reps", sets: 3, repMin: 10, repMax: 15, usesDumbbells: true },
    imageSlug: "floor-press",
    instructions: "Sit with back support. Press dumbbells forward from chest height, then return with control.",
    cues: ["Back supported", "Elbows at about 45°", "Press without locking elbows hard", "Slow return"],
    video: "https://www.youtube.com/results?search_query=seated+dumbbell+chest+press"
  },
  {
    workout: "sub",
    slug: "seated-hammer-curl",
    name: "Seated Hammer Curl",
    subtitle: "Biceps (substitute)",
    sets: "3 × 12–15",
    rest: 60,
    progression: { type: "reps", sets: 3, repMin: 12, repMax: 15, usesDumbbells: true },
    imageSlug: "hammer-curl",
    instructions: "Sit tall with dumbbells at your sides. Curl with palms facing in, keeping elbows close to your body.",
    cues: ["Back against chair", "No swinging", "Full control down", "Light weight"],
    video: "https://www.youtube.com/results?search_query=seated+hammer+curl"
  },
  {
    workout: "sub",
    slug: "tricep-kickback",
    name: "Tricep Kickback",
    subtitle: "Triceps (substitute)",
    sets: "3 × 12–15",
    rest: 60,
    progression: { type: "reps", sets: 3, repMin: 12, repMax: 15, usesDumbbells: true },
    imageSlug: "tricep-extension",
    instructions: "Hinge forward with a flat back. Keep upper arm parallel to the floor and extend the dumbbell back.",
    cues: ["Elbow stays high", "Only forearm moves", "Squeeze at the top", "Use light weight"],
    video: "https://www.youtube.com/results?search_query=dumbbell+tricep+kickback"
  }
];

export function getWorkoutExercises(letter) {
  return EXERCISES.filter((item) => item.workout === String(letter).toUpperCase());
}
